name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 17.x]
      fail-fast: false
    name: test - ${{ matrix.os }} - node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "lts/*"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
